// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_9mYHeetjHsUquLg9apjJq25E4WCJ1pM',
    appId: '1:399966120038:web:7c4fa412d5baf3db49a5a7',
    messagingSenderId: '399966120038',
    projectId: 'aggregate-test-4a035',
    authDomain: 'aggregate-test-4a035.firebaseapp.com',
    storageBucket: 'aggregate-test-4a035.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzfwM3QEGJRPry2jBgNMgq3hi6LH1OmU',
    appId: '1:399966120038:android:71f90cb2f4a149d949a5a7',
    messagingSenderId: '399966120038',
    projectId: 'aggregate-test-4a035',
    storageBucket: 'aggregate-test-4a035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXY_uOxg1HGTfRUSPmZXJyeWXEjV9i3k',
    appId: '1:399966120038:ios:f707dd38a97d1a7149a5a7',
    messagingSenderId: '399966120038',
    projectId: 'aggregate-test-4a035',
    storageBucket: 'aggregate-test-4a035.appspot.com',
    iosBundleId: 'com.example.aggregateTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXY_uOxg1HGTfRUSPmZXJyeWXEjV9i3k',
    appId: '1:399966120038:ios:f707dd38a97d1a7149a5a7',
    messagingSenderId: '399966120038',
    projectId: 'aggregate-test-4a035',
    storageBucket: 'aggregate-test-4a035.appspot.com',
    iosBundleId: 'com.example.aggregateTest',
  );
}
